# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use a recente versão estável
    hooks:
      - id: trailing-whitespace # Remove espaços em branco no final das linhas
      - id: end-of-file-fixer # Garante que os arquivos terminem com uma nova linha
      - id: check-yaml # Verifica a sintaxe de arquivos YAML
      - id: check-added-large-files # Impede o commit de arquivos grandes

  - repo: https://github.com/psf/black
    rev: 24.4.2 # Use a recente versão estável do Black
    hooks:
      - id: black
        language_version: python3.12 # Especifique sua versão do Python

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2 # Use a recente versão estável do isort
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0 # Use a recente versão estável do Flake8
    hooks:
      - id: flake8
